language: ruby
cache: bundler
addons:
  codeclimate:
    repo_token: 59d27c9fc5a1c2a9379c602aec18e6d569c6cdce39f0118ffc0e954ed6af563a
  postgresql: '9.4'
before_script:
- psql -c "create database travis_ci_test;" -U postgres
- cp config/database.travis.yml config/database.yml
deploy:
  provider: opsworks
  access_key_id: AKIAIX2XPBWY2OUEGGXA
  secret_access_key:
    secure: TKGjNiIwvkhwsFpN7aL9c2jE+HZiomkY2sF2M3xO2CnRgQSfOotaj3gGAQaG4B69zxfm5PfJ+uxbdB9oYxs1cQnSapxYquS7RGcO/Ib/22CUcvFlMyUywjUioQXcgoHzj2up9YGxj+vmS3b/T9ZGh+L5UUB0wwrn3MvTYrJWMw0=
  app-id: 1cd0a7e6-627b-4f24-80a5-fdde59ad904c
  on:
    repo: rapidturtle/com.twincresttech.www
    branch: master
